### ISSUE TITLE
List of soundfiles not loading

### ISSUE THREAD

**Issue by WitchDoctorAmI** [NitroPye/mumble-soundboard#1]
Hey,

i installed your soundboard on my server. The bot joins my mumble server just fine, the website is available as well. 

I cant upload sound files though, also the sound files i added via SCP are not showing up:

![2016-06-22 14_58_39-mumble soundboard](https://cloud.githubusercontent.com/assets/17800347/16267415/ee0731e8-3889-11e6-87ab-462888882645.png)

This happens when I try to upload a sound file via browser (the animation just keeps going, the soundbot leaves the server and joins again though).

![2016-06-22 14_58_43-mumble soundboard](https://cloud.githubusercontent.com/assets/17800347/16267436/01e48d5a-388a-11e6-9703-430c20281fa8.png)

This is my "sounds" site, although there is a sound file in my folder which I added via SCP.

I already tried using chmod 777 on the audio folder, that did not help anything (thought there might be a right management problem with accessing the audio files).

I started the docker file like this:

`sudo docker run -d --restart always -p 8080:3000 -v "/var/lib/docker/data/soundboard/:/audio" -e MUMBLE_URL="MUMBLEURL" -e MUMBLE_NAME="Tonbrettroboter" -e MUMBLE_PASS="PASSWORT" -e AUDIO_DIR="/home/simon/audio" mycatisblack/mumble-soundboard:latest
`

Edited Mumble URL and password out, but the connection to the server itself is working fine.

**Comment by coconitro** [comment]
Do you see anything in the container when you run `docker logs` against that container? If so can you paste the output into here? Thanks!

Edit: It also appears your volume mapping and audio directory are out of sync.

```
-v "/var/lib/docker/data/soundboard/:/audio"
```

Is fine, but then this

```
-e AUDIO_DIR="/home/simon/audio" 
```

tells the application that its audio directory inside the container is `/home/simon/audio`, but the volume mount is to `/var/lib/docker/data/soundboard`. 

Try running the container using the default AUDIO_DIR (the README may be unclear or lacking) like this:

```
sudo docker run -d --restart always -p 8080:3000 -v "/home/simon/audio:/audio" -e MUMBLE_URL="MUMBLEURL" -e MUMBLE_NAME="Tonbrettroboter" -e MUMBLE_PASS="PASSWORT" mycatisblack/mumble-soundboard:latest 
```

**Comment by coconitro** [comment]
Made some minor fixes to bot.js so that AUDIO_DIR had a better default and updated documentation. https://github.com/NitroPye/mumble-soundboard/pull/2

**Comment by WitchDoctorAmI** [comment]
Thank you so much, the edited start line did it for me :)
